import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Header from "./_components/Header";
import { Toaster } from "@/components/ui/sonner";

const mon = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(mon.className, "antialiased")}>
        <Header />
        {children}
        <Toaster position="top-right" />
      </body>
    </html>
  );
}
